//
// Created by Jurco on 22. 11. 2018.
//

#ifndef BOMBERMAN_CLIENT_CONSTANTS_H
#define BOMBERMAN_CLIENT_CONSTANTS_H

enum result_code {
    ZERO = 0, OK = 200, CREATED = 201, UNAUTHORIZED = 401, INTERNAL_SERVER_ERROR = 500
};

#endif //BOMBERMAN_CLIENT_CONSTANTS_H
