//
// Created by Jurco on 22. 11. 2018.
//

#ifndef BOMBERMAN_CLIENT_CONSTANTS_H
#define BOMBERMAN_CLIENT_CONSTANTS_H

enum result_code {
    ZERO = 0, OKEJ = 200, CREATED = 201, UNAUTHORIZED = 401, INTERNAL_SERVER_ERROR = 500
};

enum communication_type {
    LOGIN, CREATE_GAME, GET_LOBBY_PLAYER
};


#endif //BOMBERMAN_CLIENT_CONSTANTS_H
